export enum USERTYPE {
  ADMIN,
  NONADMIN,
}

export enum ROLETYPE {
  SUPER_ADMIN = 'SUPER_ADMIN',
  LOCATION_ADMIN = 'LOCATION_ADMIN',
  LOCATION_ASSISTANCE_ADMIN = 'LOCATION_ASSISTANCE_ADMIN',
  MANUAL_ADMIN = 'MANUAL_ADMIN',
  GENERAL = 'GENERAL',
}
